version: "3.3"
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - type: bind
        source: /home/chetan/Documents/coderepo/csvserver/solution/inputFile
        target: /csvserver/inputdata
    environment:
      CSVSERVER_BORDER: Orange
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: /home/chetan/Documents/coderepo/csvserver/solution/prometheus.yml
        target: /etc/prometheus/prometheus.yml
